name: ginkgo-test
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  ginkgo:
    name: ginkgo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - uses: actions/checkout@v2
      - run: go install -mod=mod github.com/onsi/ginkgo/v2/ginkgo
      - run: ginkgo -r -v